FROM maven:3.9.5-eclipse-temurin-21 AS build
WORKDIR /app
RUN apt-get update && apt-get install -y git
RUN git clone https://github.com/seshasaikrishnachanumolu/cicd-project-backend.git .
RUN mvn clean package -DskipTests

FROM eclipse-temurin:21-jre-alpine
WORKDIR /app
COPY --from=build /app/target/SDPProject-0.0.1-SNAPSHOT.jar app.jar
EXPOSE 8086
ENTRYPOINT ["java", "-jar", "app.jar"]
