FROM node:18 AS build

WORKDIR /app

# Clone your frontend repo
RUN git clone https://github.com/seshasaikrishnachanumolu/frontend-repo.git .

RUN npm install
RUN npm run build

FROM nginx:alpine

COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
